### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by lfmnovaes** [lfmnovaes/recipe-app#7]
#### Team-Members: ( 2 Members )
- @ramiaquista ( Team member 1 ) 
- @lfmnovaes ( Team member 2 )

**Comment by DeliceLydia** [comment]
## Hi Team, 

Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [x] Add a card for the layout of the wireframes provided
- [x] Food list:
- Should lead to the form that allows users to add new food

- [x] Recipient list:
- Should display a list of recipes created by the logged-in user as in the wireframe.
- Should lead to recipe details.
- If the user is the owner of the recipe, should allow the user to delete it.

- [x] Public recipes
- Should lead to recipe details.

- [x] Recipes details
- If the recipe is public or the user is the owner of the recipe, should display the recipe details.
- If the user is the owner of the recipe, should lead to the form that allows the user to add new food.

- [x] Shopping list view
- Should show the list of food that is missing for all recipes of the logged-in user.
- Should count the total food items and total price of the missing food.

- [x] Please add a card for N+1 queries
- [x] Add a card for the navigation menu that allows users to open all of the pages you created.



### Keep Rocking!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dasileker** [comment]
## **Hi @lfmnovaes,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
